apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: goxlogger-depl
spec:
  replicas: 1
  template:
    metadata:
      labels:
        editor: vscode
    spec:
      containers:
      - name: goxlogger
        image: goxlogger:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - name: DEBUG
          valueFrom:
            configMapRef:
              name:  debug
              key: goxlogger-config
        volumeMounts:
        - name: config-vol
          mountPath: /etc/config
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        containerPort:
        - name: goxlogger-port
          port: "9000"
      volumes:
      - name: log-config
        configMap:
          name: log-config
          items:
            - key: log_level
              path: log_level.conf       
