services:
  xlogger:
    build: ./goxlogger
    container_name: xlogger-app
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/app/config.yaml
    networks:
      - xlogger

  redis:
    image: redis:latest
    container_name: xlogger-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "6379:6379"
    networks:
      - xlogger

networks:
  xlogger:
    driver: bridge
