allowBuilds:
  '@firebase/util': set this to true or false
  '@parcel/watcher': false
  '@tailwindcss/oxide': false
  esbuild: false
  protobufjs: set this to true or false
  unrs-resolver: false
  vue-demi: false
